### ISSUE TITLE
Unable to login using google apps

### ISSUE THREAD

**Issue by bamuis** [waj/redmine_google_apps#2] opened 2012-01-27 18:39 UTC
After installing the plugin I am unable to login using my google apps account.

previously i could login using google open ID. however the problem was that it was automatically creating users irrespective of the authentication settings. Also I could no way restrict which domain users can login.

After installing this plugin I had to rename the directory redmine_google_apps to google_apps to get my redmine started.

After that when I add my domain, I see a link on the home page which says login with domain account.

However when I click on that link I get this error "Sorry, the OpenID server couldn't be found"

Also I see the following in the logs

Processing GoogleAppsController#login (for 127.0.0.1 at 2012-01-28 00:04:18) [GET]
  Parameters: {"action"=>"login", "domain"=>"1", "controller"=>"google_apps"}
WARNING: making https request to https://www.google.com/accounts/o8/site-xrds?hd=www.domain.com without verifying server certificate; no CA path was specified. <I have replaced my domain name in this post to www.domain.com>
[OPENID] HTTP Response status from identity URL host is not "200".Got status "400" for https://www.google.com/accounts/o8/site-xrds?hd=www.domain.com 
Redirected to http://localhost/redmine/login
Completed in 288ms (DB: 0) | 302 Found [http://localhost/redmine/google_apps/login?domain=1]

Processing AccountController#login (for 127.0.0.1 at 2012-01-28 00:04:18) [GET]
  Parameters: {"action"=>"login", "controller"=>"account"}
Rendering template within layouts/base
Rendering account/login
Completed in 176ms (View: 171, DB: 0) | 200 OK [http://localhost/redmine/login]

Can you please help me to fix this problem.

**Comment by waj** [comment] 2012-01-27 18:43
Try setting the domain name to "domain.com" instead of "www.domain.com".

Sorry about the directory name. I'll clarify that on the README file.

**Comment by bamuis** [comment] 2012-01-27 19:04
Thanks for the quick revert. It now goes to the login page of my domain. However when I enter my domain username and password it says "open id verification failed" on my local redmine login.

i have set Self-registration as "Manual Account Activation" I see the error in logs as "Error attempting to use stored discovery information: OpenID::TypeURIMismatch"

Pasting the logs below

Processing GoogleAppsController#login (for 127.0.0.1 at 2012-01-28 00:29:47) [GET]
  Parameters: {"action"=>"login", "domain"=>"2", "controller"=>"google_apps"}
WARNING: making https request to https://www.google.com/accounts/o8/site-xrds?hd=domain.com without verifying server certificate; no CA path was specified.
Generated checkid_setup request to https://www.google.com/a/domain.com/o8/ud?be=o8 with assocication AMlYA9XJLjhnn9jKZ0lDOtpIBh6P8gf_cCASl7AsGuS4b1sscE_eRI6R
Redirected to https://www.google.com/a/domain.com/o8/ud?be=o8&openid.assoc_handle=AMlYA9XJLjhnn9jKZ0lDOtpIBh6P8gf_cCASl7AsGuS4b1sscE_eRI6R&openid.ax.mode=fetch_request&openid.ax.required=ext0%2Cext1%2Cext2&openid.ax.type.ext0=http%3A%2F%2Faxschema.org%2FnamePerson%2Flast&openid.ax.type.ext1=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ax.type.ext2=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.ax=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.realm=http%3A%2F%2Flocalhost%2Fredmine%2F&openid.return_to=http%3A%2F%2Flocalhost%2Fredmine%2Fgoogle_apps%2Flogin%3Fdomain%3D2%26_method%3Dget%26open_id_complete%3D1
Completed in 728ms (DB: 5) | 302 Found [http://localhost/redmine/google_apps/login?domain=2]

Processing GoogleAppsController#login (for 127.0.0.1 at 2012-01-28 00:29:49) [GET]
  Parameters: {"openid.mode"=>"id_res", "openid.op_endpoint"=>"https://www.google.com/a/domain.com/o8/ud?be=o8", "openid.return_to"=>"http://localhost/redmine/google_apps/login?domain=2&_method=get&open_id_complete=1", "openid.sig"=>"6fcNMRGPtD8lbK6SRX+SI+KvwLA=", "openid.response_nonce"=>"2012-01-27T18:59:49ZyEoOLayFSei9mQ", "openid.ns"=>"http://specs.openid.net/auth/2.0", "openid.ext1.value.ext0"=>"Basheer", "action"=>"login", "domain"=>"2", "_method"=>"get", "openid.ext1.mode"=>"fetch_response", "openid.ext1.value.ext1"=>"Mohammad", "openid.identity"=>"http://domain.com/openid?id=117971754041234022029", "openid.ext1.value.ext2"=>"basheer@domain.com", "openid.ext1.type.ext0"=>"http://axschema.org/namePerson/last", "openid.ext1.type.ext1"=>"http://axschema.org/namePerson/first", "openid.assoc_handle"=>"AMlYA9XJLjhnn9jKZ0lDOtpIBh6P8gf_cCASl7AsGuS4b1sscE_eRI6R", "openid.signed"=>"op_endpoint,claimed_id,identity,return_to,response_nonce,assoc_handle,ns.ext1,ext1.mode,ext1.type.ext1,ext1.value.ext1,ext1.type.ext2,ext1.value.ext2,ext1.type.ext0,ext1.value.ext0", "openid.ns.ext1"=>"http://openid.net/srv/ax/1.0", "openid.ext1.type.ext2"=>"http://axschema.org/contact/email", "controller"=>"google_apps", "open_id_complete"=>"1", "openid.claimed_id"=>"http://domain.com/openid?id=117971754041234022029"}
Error attempting to use stored discovery information: OpenID::TypeURIMismatch
Attempting discovery to verify endpoint
Performing discovery on http://domain.com/openid?id=117971754041234022029
Redirected to http://localhost/redmine/login
Completed in 1739ms (DB: 0) | 302 Found [http://localhost/redmine/google_apps/login?domain=2&_method=get&open_id_complete=1&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Fa%2Fdomain.com%2Fo8%2Fud%3Fbe%3Do8&openid.response_nonce=2012-01-27T18%3A59%3A49ZyEoOLayFSei9mQ&openid.return_to=http%3A%2F%2Flocalhost%2Fredmine%2Fgoogle_apps%2Flogin%3Fdomain%3D2%26_method%3Dget%26open_id_complete%3D1&openid.assoc_handle=AMlYA9XJLjhnn9jKZ0lDOtpIBh6P8gf_cCASl7AsGuS4b1sscE_eRI6R&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.ext1%2Cext1.value.ext1%2Cext1.type.ext2%2Cext1.value.ext2%2Cext1.type.ext0%2Cext1.value.ext0&openid.sig=6fcNMRGPtD8lbK6SRX%2BSI%2BKvwLA%3D&openid.identity=http%3A%2F%2Fdomain.com%2Fopenid%3Fid%3D117971754041234022029&openid.claimed_id=http%3A%2F%2Fdomain.com%2Fopenid%3Fid%3D117971754041234022029&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.ext1=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.ext1=Mohammad&openid.ext1.type.ext2=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.ext2=basheer%40domain.com&openid.ext1.type.ext0=http%3A%2F%2Faxschema.org%2FnamePerson%2Flast&openid.ext1.value.ext0=Basheer]

Processing AccountController#login (for 127.0.0.1 at 2012-01-28 00:29:51) [GET]
  Parameters: {"action"=>"login", "controller"=>"account"}
Rendering template within layouts/base
Rendering account/login
Completed in 48ms (View: 45, DB: 0) | 200 OK [http://localhost/redmine/login]

**Comment by waj** [comment] 2012-01-27 19:13
It seems like you have the same issue mstonis has (https://github.com/waj/redmine_google_apps/issues/1), but I still cannot figure out what's going on.
I'll set up a new environment from scratch to see if I can reproduce the problem. Which version of Redmine are you running?

**Comment by bamuis** [comment] 2012-01-27 19:16
I am using redmine 1.2

**Comment by acdaniel** [comment] 2012-01-27 20:32
I ran into the same issue as bamuis and mstonis with a clean redmine environment.  After a few days of troubleshooting, I have everything working perfectly.  

After wading through the open_id_authentication code in vendor/plugins (which is version 2.0.4), I realized the google_apps_controller in the google_apps plugin is expecting a response object as the first returned value from authenticate_with_open_id on line 14.  However, the version of open_id_authentication I have yields a message string instead.  I modified line 15 in google_apps_controller to "unless profile_data.nil?" and line 39 to "flash[:error] = result".  That got past the server errors.

I was still getting "OpenID verification failed" so I modified open_id_authentication.rb line 176 to yield "open_id_response.message" instead of the extremely generic and unhelpful "verification failed" message.

After doing all that I was able to see exactly what was happening and it lead me to this article:  http://jeremiahlee.com/blog/2009/09/28/how-to-setup-openid-with-google-apps/

After I added the files to my website, verification was still failing.  I was able to track it down to a redirect that I had on my server.  All traffic to mysite.com was being redirected to www.mysite.com but the verification process will not follow the redirect.  I modified  the redirect to go from www.mysite.com to mysite.com and everything works perfectly now.

I hope this helps.

**Comment by bobpaul** [comment] 2012-01-28 00:18
I seem to be having the same problem. I can log in with my open id url, I can log in with my username/password, but if I try to click the google_apps link, it fails and put this in the log:
Error attempting to use stored discovery information: OpenID::TypeURIMismatch
Attempting discovery to verify endpoint
Performing discovery on http://REDACTED.com/openid?id=103545903996079910852
Redirected to http://redmine.REDACTED.com/login

using redmine 1.3.0 from gentoo portage
google_apps version is Jan 24th's commit (98fd9882)

acdaniel: can you be more specific on what you did? 
On line 177 I have:
`yield Result[:failed], identity_url, nil`
which I changed to 
`yield open_id_response.message, identity_url, nil`
which is causing some error (NoMethodError (undefined method `successful?' for #String:0x7f0347aad538):)

With regards to the redirect thing you did (assuming that's also my problem), this was something you had to change your webserver (apache, or whatever) and not in redmine specifically?

**Comment by acdaniel** [comment] 2012-01-28 04:06
bobpaul, the change you made will allow a more specific error message to be passed along to the `google_apps_controller`.  What I did next was modify `google_apps_controller` to accept the string that is being returned from `authenticate_with_open_id`. I changed 2 lines starting at line 15:

```
unless profile_data.nil?    # this used to be: 'if result.success?' but result isn't an object 
    ...
else 
    flash[:error] = result    # this used to be: 'flash[:error] = result.message
    ...
end
```

Now when you try to authenticate you should get a nice descriptive error if it fails.

As far as the redirect, I had to modify the `.htaccess` in the site that matches my google apps domain.  The discovery process requests `http://REDACTED.com/openid?id=123456789012345`.  Because of rules in my `.htaccess` file, the request was being redirected to `http://www.REDACTED.com/openid?id=123456789012345` which the discovery process did not like at all. So my `.htaccess` file now has the following rule:

```
RewriteCond %{HTTP_HOST} ^www\.               [NC]
RewriteCond %{HTTP_HOST} ^www\.([^.]+\.[a-z]{2,6})$ [NC]
RewriteRule ^(.*)$       http://%1/$1      [R=301,L,QSA]
```

The redirect has nothing to do with redmine it was just apparently stopping the openID discovery process.

**Comment by waj** [comment] 2012-01-28 17:26
Thanks acdaniel! I had followed the exact same instructions from that page (http://jeremiahlee.com/blog/2009/09/28/how-to-setup-openid-with-google-apps/) two years ago and I just forgot that I did.

However, as explained by Google here: https://sites.google.com/site/oauthgoog/fedlogininterp/openiddiscovery, that procedure should not be mandatory. So I've been researching a little bit more and I found this gem: http://code.google.com/p/ruby-openid-apps-discovery.

So I added that dependency and now the plugins should work without even having your domain hosted anywhere.

Please update your plugins's code and install the gem 'ruby-openid-apps-discovery' and try again. I tested it on my environment and works fine. I'll update the README file shortly.

Also, I'll reinstall previous versions of Redmine to figure out incompatibilities with the openid plugin.

Thank you guys!

**Comment by michaelstonis** [comment] 2012-01-28 19:13
Created the additional files per the openid setup guide and installed the ruby-openid-apps-discovery gem and everything looks to be good now.

One note, if you have a local user account with the same name as a google apps user, it will not create the account. Not an issue at all, but worth noting.

**Comment by bobpaul** [comment] 2012-01-28 19:28
Mine seems to be working, now, too. Thanks waj!

> One note, if you have a local user account with the same name as a google apps user, it will not create the account. Not an issue at all, but worth noting.

Ok, good, that _is_ an unrelated issue. Unfortunately, all of our accounts were local before we got Google apps. Is there a workaround for this? With the standard OpenID plugin it would show the user-specific OpenID URL and users could paste that into the "My Account" page. How do we get google_apps to authenticate for pre-existing users?

**Comment by waj** [comment] 2012-01-28 19:33
Actually the Google Apps plugin searches users by email. So if your existing users have the right email address you should be fine.

I'll close this issue. Let's open new ones for unrelated things.

Thanks!

**Closed as completed by waj** 2012-01-28 19:33 UTC

**Comment by bobpaul** [comment] 2012-01-28 19:35
Nevermind;  I got it.

Logged in as a Redmine admin user, choose
Administration->Users->Username->Authentication Mode: Internal and change it to your domain. It seems a given user can only use either their username/password OR authentication via the domain (not either, as with the standard openid plugin that ships with Redmine)

**Comment by bamuis** [comment] 2012-01-29 02:43
I still have the same issue. same error in log file. only difference is that on home page it says "There was an error creating your account. Please contact your administrator."

I have installed the gem and reinstalled the google_apps plugin.

Any other settings to be done?

**Comment by bamuis** [comment] 2012-01-29 04:33
just to add, I am able to register using google open id with the same google apps account.

I would like to allow only my domain users to register and login while all other open id's are disabled.

Also I am running redmine on localhost. my url reads as http://localhost/redmine

**Comment by bobpaul** [comment] 2012-01-30 02:28
> I still have the same issue. same error in log file. only difference is that on home page it says "There was an error creating your account. Please contact your administrator."

If you see that, it's working but another account already exists with the same email address as the one you're trying to login with/create. See my last comment about changing Authentication Mode to enable google_apps authentication for an existing user.

**Comment by bamuis** [comment] 2012-01-30 06:05
Nope. I dont have user with that email address.
